### ISSUE TITLE
Wireless Receiver

### ISSUE THREAD

**Issue by victorperin** [Jabbath/node-xboxdrv#1]
I'm trying to connect node with the xbox wireless controller, but i couldn't make it work.
It work with the wireless controllers?

**Comment by antonafana** [comment]
You should now be able to pass in a third argument of {"type": "xbox360-wireless"}. Assuming everything else works the same for wireless controllers, you should be able to use this for a wireless xbox 360 controller.

[Commit](https://github.com/Jabbath/node-xboxdrv/commit/6541cda75422d3a0017c61eb52440193b28ef5af)

**Comment by victorperin** [comment]
Alright thanks!
I'm going to try it here...

**Comment by victorperin** [comment]
## Update

Worked very well! Thanks again!
So, I'm running it at a raspberry pi and it's working very well, I just need to call:  rmmod xpad every startup, so it could be helpfull if someone have the same issue...
